# Generated by Django 5.1.1 on 2024-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_kutubxonachi_muallif_kitob_soni_muallif_t_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutubxonachi',
            name='ish_vaqti',
            field=models.CharField(choices=[('1', '8:00 - 13:00'), ('2', '13:00 - 19:00')], max_length=40),
        ),
    ]
